server:
  port: 8080
spring:
  application:
    name: changJiang
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.128:3306/changJiang?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root